name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.3'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Print Environment Variables
      run: printenv | sort

    - name: Print OPENAI_API_KEY
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"

    - name: Run the default task
      run: bundle exec rake
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}